name: workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pymol-open-source
  - pip
  - pip:
      - biopython
      - python-dotenv
      - pandas
      - numpy
      - matplotlib
      - loguru
      - py3dmol
      - requests
      - rdkit